// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQdZbDQzmexdp13FN1Cj6D5vieScU-qE',
    appId: '1:168100674425:web:24945e9f3f2273ce9b0da8',
    messagingSenderId: '168100674425',
    projectId: 'classorganizer-b6c6f',
    authDomain: 'classorganizer-b6c6f.firebaseapp.com',
    databaseURL: 'https://classorganizer-b6c6f-default-rtdb.firebaseio.com',
    storageBucket: 'classorganizer-b6c6f.appspot.com',
    measurementId: 'G-1QC9SZ06GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkKHRN_VCgd4iwmkJmJ_qs_wVU9m4HLpE',
    appId: '1:168100674425:android:09e9f744892909b39b0da8',
    messagingSenderId: '168100674425',
    projectId: 'classorganizer-b6c6f',
    databaseURL: 'https://classorganizer-b6c6f-default-rtdb.firebaseio.com',
    storageBucket: 'classorganizer-b6c6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyXBw3KsJ7lcUrT618C3lYHKJSvJZnvtc',
    appId: '1:168100674425:ios:fe1378346cb94f8a9b0da8',
    messagingSenderId: '168100674425',
    projectId: 'classorganizer-b6c6f',
    databaseURL: 'https://classorganizer-b6c6f-default-rtdb.firebaseio.com',
    storageBucket: 'classorganizer-b6c6f.appspot.com',
    iosBundleId: 'com.example.classOrganizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkQdZbDQzmexdp13FN1Cj6D5vieScU-qE',
    appId: '1:168100674425:web:00982f32f3b6e22f9b0da8',
    messagingSenderId: '168100674425',
    projectId: 'classorganizer-b6c6f',
    authDomain: 'classorganizer-b6c6f.firebaseapp.com',
    databaseURL: 'https://classorganizer-b6c6f-default-rtdb.firebaseio.com',
    storageBucket: 'classorganizer-b6c6f.appspot.com',
    measurementId: 'G-5RDYHGH7SE',
  );
}
